In [1]:
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import matplotlib.pyplot as plt



In [2]:
#Creating the basick modell


class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_stack =  nn.Sequential(
         nn.Linear(1,15),
         nn.ReLU(),
         nn.Linear(15,15),
         nn.ReLU(),
         nn.Linear(15,15),
         nn.ReLU(),
         nn.Linear(15,1),
         )
    def forward(self,x):
        logits = self.linear_stack(x)
        return logits



In [4]:
#create train_set
batch_size = 10000 #increasing batch size, helped for getting a more acruate result
X = torch.rand(batch_size,1)
Y = X**2



In [7]:
model = NeuralNetwork()

In [101]:
#Define Hyperparameters
lr = 0.01
optim = torch.optim.Adam(model.parameters(), lr=lr)

loss = torch.nn.MSELoss()
n_iters = 10000


In [102]:
# Training loop
for epochs in range(n_iters):
    #forward pass and loss
    out = model(X)
    l = loss(out,Y)
    #backward pass
    l.backward()
    #update weights
    optim.step()
    optim.zero_grad()

    if epochs % 100 == 0:
        print(f" {epochs+1}, l={l.item()}")


 1, l=6.960223686292011e-07
 101, l=1.7113869716922636e-06
 201, l=1.0160987358176499e-06
 301, l=8.720264759176644e-07
 401, l=7.519925020460505e-07
 501, l=6.383802997333987e-07
 601, l=5.384660539675679e-07
 701, l=4.789724812326313e-07
 801, l=4.535807249794743e-07
 901, l=4.3546381789383304e-07
 1001, l=4.200278738153429e-07
 1101, l=4.0524327005186933e-07
 1201, l=3.9151311170826375e-07
 1301, l=3.7854778156543034e-07
 1401, l=3.6640960843215e-07
 1501, l=3.543915454429225e-07
 1601, l=3.42597076041784e-07
 1701, l=3.3168592494803306e-07
 1801, l=3.299728632555343e-07
 1901, l=4.1507104242555215e-07
 2001, l=3.29004109289599e-07
 2101, l=6.645585131082044e-07
 2201, l=3.387455933534511e-07
 2301, l=7.038004696369171e-05
 2401, l=4.082123723492259e-07
 2501, l=3.3703747703839326e-07
 2601, l=0.00010218957322649658
 2701, l=3.8219801012928656e-07
 2801, l=3.205010727924673e-07
 2901, l=3.5117332117806654e-06
 3001, l=3.3007151500896725e-07
 3101, l=2.9710329840781924e-07
 3201, l=9

In [103]:
test_cases = 10
for i in range(test_cases):
    X_test = torch.rand(1,1)
    print(f"Real outcome : {(X_test**2).item():.2f}; Predicted output : {model(X_test).item():.2f}")
    print(f"")

Real outcome : 0.06; Predicted output : 0.06

Real outcome : 0.06; Predicted output : 0.06

Real outcome : 0.48; Predicted output : 0.48

Real outcome : 0.23; Predicted output : 0.23

Real outcome : 0.46; Predicted output : 0.46

Real outcome : 0.71; Predicted output : 0.71

Real outcome : 0.19; Predicted output : 0.19

Real outcome : 0.43; Predicted output : 0.43

Real outcome : 0.07; Predicted output : 0.07

Real outcome : 0.36; Predicted output : 0.36



In [110]:
#calculate accuracy
test_cases = 100
correct_count = 0
y = []
y_predicted = []
for i in range (test_cases):
    X_test = torch.rand(1,1)
    y.append(torch.round(X_test**2,decimals=2))
    y_predicted.append(torch.round(model(X_test), decimals=2))
    
count = 0   
for i in range(test_cases):
    if y_predicted[i] == y[i]:
        count += 1
print(f"Accuracy of model : {(count/test_cases)*100} %")

Accuracy of model : 95.0 %


[tensor([[0.1900]], grad_fn=<RoundBackward1>),
 tensor([[0.3400]], grad_fn=<RoundBackward1>),
 tensor([[0.1600]], grad_fn=<RoundBackward1>),
 tensor([[0.1200]], grad_fn=<RoundBackward1>),
 tensor([[0.6000]], grad_fn=<RoundBackward1>),
 tensor([[0.0600]], grad_fn=<RoundBackward1>),
 tensor([[0.5800]], grad_fn=<RoundBackward1>),
 tensor([[0.0400]], grad_fn=<RoundBackward1>),
 tensor([[0.6100]], grad_fn=<RoundBackward1>),
 tensor([[0.4200]], grad_fn=<RoundBackward1>),
 tensor([[0.2300]], grad_fn=<RoundBackward1>),
 tensor([[0.0300]], grad_fn=<RoundBackward1>),
 tensor([[0.4400]], grad_fn=<RoundBackward1>),
 tensor([[-0.]], grad_fn=<RoundBackward1>),
 tensor([[0.8500]], grad_fn=<RoundBackward1>),
 tensor([[0.]], grad_fn=<RoundBackward1>),
 tensor([[0.6600]], grad_fn=<RoundBackward1>),
 tensor([[0.3700]], grad_fn=<RoundBackward1>),
 tensor([[0.6200]], grad_fn=<RoundBackward1>),
 tensor([[0.1200]], grad_fn=<RoundBackward1>),
 tensor([[0.2800]], grad_fn=<RoundBackward1>),
 tensor([[0.8500]], 